
# colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

LIVE = WHITE
DEAD = BLACK

# blocks
BLOCKS_X = 40
BLOCKS_Y = 40
BLOCK_LENGTH = 10
BORDER_THICKNESS = 1

# dimensions
WINDOW_WIDTH = (BORDER_THICKNESS + BLOCK_LENGTH) * BLOCKS_X + BORDER_THICKNESS
WINDOW_HEIGHT = (BORDER_THICKNESS + BLOCK_LENGTH) * BLOCKS_Y + BORDER_THICKNESS

TICK_TIME = 0.5
